spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.102.153.227:3306/miniProduct01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: '!QAZ2wsx'
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
