spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/miniProduct01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 3160411057
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
